version : 2
jobs :
    build :
        working_directory : ~/mulesoft-builds
        docker :
            - image : circleci/openjdk:8-jdk-browsers
        steps :
            - checkout
            - restore_cache :
                key : circleci -m2 -cache
            - run :
                name : Build the API .
                command : mvn -s .circleci.settings.xml -DskipMunitTests clean package
            - save_cache :
                paths :
                    - ~/.m2
                key : circleci -m2 -cache

    test :
        working_directory : ~/mulesoft-builds
        docker :
            - image : circleci/openjdk:8-jdk-browsers
        steps :
            - checkout
            - restore_cache :
                key : circleci -m2 -cache
            - run :
                name : Run the MUnit Tests for this API
                command : mvn -s .circleci.settings.xml clean test
            - save_cache :
                paths :
                    - ~/.m2
                key : circleci -m2 -cache
    deploy :
        working_directory : ~/mulesoft-builds
        docker :
            - image : circleci/openjdk:8-jdk-browsers
        steps :
            - checkout
            - restore_cache :
                key : circleci -m2 -cache
            - run :
                name : Deploy the API on CloudHub SANDBOX environment .
                command : mvn -s .circleci.settings.xml deploy -DmuleDeploy -Danypoint.username=$USERNAME -Danypoint.password=$PASSWORD -Dcloudhub.environment=Sandbox
            - save_cache :
                paths :
                - ~/.m2
                key : circleci -m2 -cache
workflows :
    version : 2
    build_test_and_deploy :
      jobs :
        - build
        - test
        - deploy